### PR TITLE
Secure webhook and add more descriptive commit notifications

### PR DESCRIPTION
**Pull request by amingilani**
Hey

I studied RabbitBot for my own Hubot and learnt a lot about Github webhooks. I thought I'd help you guys out. Here's the code I used to secure the webhooks for [payloadpk/paybot](https://github.com/payloadpk/paybot)

Thanks!

### CODE REVIEW

**Comment by fabianthoma** [comment]
Oh, interesting. We currently don't really use the github hooks, but I'll see what code I can reuse from you.

**Comment by amingilani** [comment]
Actually, I your code was the first example I saw of the event emitter, pretty nifty. Sure thing, use whatever, it's all good.

**Comment by fabianthoma** [comment]
Wow, this looks actually pretty good, how about abstracting this into a hubot-module for everyone to use? I think I'll do that in the next few days. Untill that is done I'll merge this into rabbitbot.

**Comment by amingilani** [comment]
The thought did cross my mind actually, but I'll do that once I've settled on exactly what sort of messages I want my robot to give for events. I'm experimenting with deploy messages, and pull request messages right now.. haven't found the right one.

Feel free to write your own in the mean time :smile:

**Pull request merged**
